### ISSUE TITLE
Support for loading bower CSS librairies

### ISSUE THREAD

**Issue by benjbdev** [tmaximini/ionic-gulp-seed#10]
I would like to say first : Good job ;)
There is any way to inject in index.html css components like font-awesome ?
Thanks !

**Comment by benjbdev** [comment]
vendor.json only working for scripts, maybe it's possible to add a "vendor-styles.json" to the gulpfile ?

**Comment by tmaximini** [comment]
hi @benjaminb- 
the way I deal usually with 3rd party scripts is to copy over files, e.g. into `app/styles/lib` and then `@import` them into my main .scss file.
you just need to copy over the actual fonts also into `app/fonts` and change the extension from .css to .scss - a bit of manual work but it is usually pretty straight forward.
You could definitely also create another .json file with a list and stream/compile them into the build, but that would involve some adjustments on the gulp job. 
let me know if the first approach works for you.

**Comment by benjbdev** [comment]
thanks i will try !
