### ISSUE TITLE
Error on gulp select

### ISSUE THREAD

**Issue by byronalfonso** [tmaximini/ionic-gulp-seed#13]
Hi everyone! First of all, thanks for this wonderful Ionic-gulp-seed. I find it very useful/helpful on my project. As I'm using this, I tried using the "gulp select" command on mac but I received this error -> 
![screen shot 2015-10-13 at 5 44 26 pm](https://cloud.githubusercontent.com/assets/11499179/10451354/3599c9be-71d2-11e5-8051-2336d74d9658.png)

has anyone got this same error?

**Comment by tmaximini** [comment]
hi @byronalfonso
I suggest you use the [yeoman generator](https://github.com/tmaximini/generator-ionic-gulp) instead, it is more up-to-date. 
If not try to use `sudo gulp select` or try to `sudo chmod 755 ./helpers/emulateios` to allow the helper to be executed.

**Comment by byronalfonso** [comment]
Hi @tmaximini! I was actually already using the yeoman generator when I tried the gulp select and I've also already tried the sudo 'gulp select' when the error happened. Your last suggestion is what worked for me though. It is now working and I'm now able to choose specific device. Many thanks and keep up the good work bro!
