### ISSUE TITLE
How do I add cordova plugins?

### ISSUE THREAD

**Issue by prashcr** [tmaximini/ionic-gulp-seed#14]
What should I do after `ionic plugin add`?

I looked at the gulpfile and it didn't seem like scripts from the plugin folder get built.

**Comment by tmaximini** [comment]
hi @prashcr 
first of all I recommend you use the [yeoman generator](https://github.com/tmaximini/generator-ionic-gulp), as it is more up to date.
You just do `ionic plugin add xyz` and after install you can use the plugin in your code. Just remember you won't be able to use it while developing in the browser, as cordova can only run on the device or any simulators.
[ng-cordova](http://ngcordova.com/) is a collection of recommended plugins for most use-cases when working with ionic and it is already included in my seed, so I suggest you take a look around, as their documentation is very good.
I hope that helps and if you have anymore questions let me know.
