### ISSUE TITLE
external css

### ISSUE THREAD

**Issue by DrSensor** [tmaximini/ionic-gulp-seed#16]
How to add external css resource ?

**Comment by byronalfonso** [comment]
My recommendation is you create a sass file module for example module.scss and include/import it on the main.scss file (found in app/styles). After you have imported the styles you want, you can run "gulp styles" on  the cli and everything will automatically compile to www/styles/main.css

note\* you can find "styles" task on line 77 of gulpfile.js

**Comment by tmaximini** [comment]
:+1:  what @byronalfonso said basically. main.scss takes care of all the imports. just save your external .css file as .scss and import it there.

**Comment by DrSensor** [comment]
Thanks, i've just realized it can be renamed to .scss.
