### ISSUE TITLE
Issue with CORS fix

### ISSUE THREAD

**Issue by xlozinguez** [tmaximini/ionic-gulp-seed#5]
Hey there, 

First of, thanks for the awesome work! Saved me a lot of time.

I am encountering a CORS issue when developing with the browser as it seems that `ionic.project` proxies configuration doesn't seem to be supported when running the `gulp` command. I believe the issue lays in the way Express is used at https://github.com/tmaximini/ionic-gulp-seed/blob/master/gulpfile.js#L237 since running `ionic serve` will work.

Do you have any idea how to fix this? 

Thanks again!

X

**Comment by tmaximini** [comment]
hey @xlozinguez 
thanks for reporting this. I will look into proxies and see if I can integrate them somehow.
A temporary workaround until then is starting your Chrome browser from the terminal like this `open -a Google\ Chrome --args --disable-web-security`, which is obviously not the prettiest solution but it will not give you any CORS errors running like this.

**Comment by xlozinguez** [comment]
Thanks @tmaximini it does the trick indeed (I had tried it before but it wasn't working for some reason).
