### ISSUE TITLE
Adding new Bower dependency

### ISSUE THREAD

**Issue by xlozinguez** [tmaximini/ionic-gulp-seed#7]
Hey @tmaximini, 

It seems that if I edit my bower.json file to add `http://libraries.io/bower/ng-cordova-http` and I run `bower install` it does not actually add the file to the `bower_components` folder. Is that normal?

As a results, when running gulp, it fails to find the library...

Let me know,

Thanks again for your work,

Xavier

**Comment by tmaximini** [comment]
it is probably not a bower url. just do `bower install ng-cordova-http --save` and it will download the package and also persist the dependency in `bower.json`.

**Comment by tmaximini** [comment]
Also make sure you add any new 3rd party javascript (e.g. from an installed bower package) into `vendor.json` - the vendor.js file gets generated from the files listed in there.

**Comment by xlozinguez** [comment]
The issue seems to have been with bower cache... I cleaned up the cache and reinstalled the dependencies, added the package to the vendor.json and now it works :+1: 
Thanks a lot @tmaximini!
