### ISSUE TITLE
Type error after migrating to ionic-gulp-seed

### ISSUE THREAD

**Issue by fi5u** [tmaximini/ionic-gulp-seed#9]
Hi,

I decided to move my Ionic app over to using ionic-gulp-seed. However, after the `gulp` build process I get several _type errors_ in the browser console.

Specifically it prints 22 times this error: 
`TypeError: Cannot read property '' of undefined`

The root of the error comes from Angular's bootstrapping function from the AngularJS file. I didn't have this error before I migrated over. The strange thing is that I have exactly 22 javascript files in the apps/scripts directory.

I wondered if you know straight away what might be causing this, before I start seriously debugging it?

Thanks

**Comment by fi5u** [comment]
I fixed this problem by replacing the individual ionic library components with _ionic.bundle.js_ (which is what I was using in my original setup). Not sure why the individual compenents caused the problem when bundle.js works fine.

**Comment by tmaximini** [comment]
Hi,

sounds like maybe some external resources were not loaded correctly. Make sure bower installs everything correctly and check `vendor.json` where you have to tell gulp which external files should go into the compiled `vendor.js`. maybe something your app required was not listed there. Anyway, glad you got it sorted out.
